# Generated by Django 2.2.10 on 2021-10-12 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('text', 'Текст'), ('OneAnswer', 'Один ответ'), ('ManyAnswer', 'Много ответов')], max_length=50, null=True)),
                ('text', models.CharField(max_length=150, verbose_name='Текст вопроса')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование опроса')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('stop', models.DateTimeField(blank=True, null=True, verbose_name='Закончен')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Question')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Ответ на вопрос')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('date_end', models.DateTimeField(auto_now_add=True, verbose_name='Время окончания')),
                ('Survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Survey')),
                ('answer_question', models.ManyToManyField(to='mainapp.AnswerQuestion')),
            ],
        ),
    ]
