# Generated by Django 2.2.10 on 2021-10-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211012_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='Survey',
            new_name='survey',
        ),
        migrations.AlterField(
            model_name='survey',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='questions', to='mainapp.Question'),
        ),
    ]
