# Generated by Django 2.2.10 on 2021-10-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211013_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='stop',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание'),
        ),
    ]
